### ISSUE TITLE
'system' is unavailable: not available on iOS

### ISSUE THREAD

**Issue by ghost** [Keemotion/TS2MP4#13]
- lib: GPAC4iOS
- file: os_devers.c at line 415
- code:
return ( system(cmd) == 0) ? GF_OK : GF_IO_ERR;
the error is: 'system' is unavailable: not available on iOS
- XCode: 9.0
please help me!

**Comment by valerianb** [comment]
Indeed, the last published version of the pod has this issue.

Please look at the solution provided on issue #12 

Thanks

**Comment by ghost** [comment]
Hello @valerianb , GPAC4iOS version still is 0.2.1 from CoCoaPod (isn't 0.2.2)

**Comment by valerianb** [comment]
Yes, that's why you should follow these instructions in the meantime:

you can check out both TS2MP4 and GPAC4iOS projects and use them this way:
```
pod 'GPAC4iOS', :path => '/path/to/project/GPAC4iOS'
pod 'TS2MP4', :path => '/path/to/project/TS2MP4'
```

In your local TS2MP4 checkout, comment line 28:
```
#s.dependency 'GPAC4iOS', '0.2.2'
```
