### ISSUE TITLE
'system' is unavailable: not available on iOS 

### ISSUE THREAD

**Issue by xiaohange** [Keemotion/TS2MP4#16]

**Comment by valerianb** [comment]
Please read https://github.com/Keemotion/TS2MP4/issues/12#issuecomment-326514743
Also note that this project isn't maintained and should not be used in production.

**Comment by xiaohange** [comment]
@valerianb Can you put a demo, it’s been a whole day, please help me.

**Comment by valerianb** [comment]
There is a Demo target in the project:
https://github.com/Keemotion/TS2MP4/blob/master/Project/TS2MP4Demo/KMExportViewController.m

**Comment by xiaohange** [comment]
@valerianb 
<img width="565" alt="2018-08-30 6 35 36" src="https://user-images.githubusercontent.com/14025157/44846664-94af2680-ac83-11e8-9d82-9f43c568ffe1.png">
